#!/bin/sh
# Uses xwinwrap to display given animated .gif in the center of the screen

if [ $# -ne 1 ]; then
  echo 1>&2 Usage: $0 image.gif
  exit 1
fi

#get screen resolution
#SCRH=($(xrandr | awk '/current/ { print $8 }')/2)
#SCRW=$(xrandr | awk '/current/ { print $10 }')
#SCRW=${SCRW%\,}

#get gif resolution
#IMGHW=$(gifsicle --info $1 | awk '/logical/ { print $3 }')
#IMGH=${IMGHW%x*}
#IMGW=${IMGHW#*x}

#           1920x1080+0+0 : width x height + posX + posY
xwinwrap -g 1920x1080+0+0 -ov -ni -s -nf -- gifview -w %WID $1 -a

exit 0
